/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package successBtn;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Akila
 */
public class btnContainer extends javax.swing.JPanel {

    /**
     * Creates new form btnContainer
     */
    public btnContainer() {
        initComponents();
    }

    
    public void initEvents(TableBtnActionEvent event, int row){
        correctBtn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                chageTextColour();
                System.out.println("abc abc ab cba c");
                event.onBtnEdit(row);
            }
            
        });
        discardBtn.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onBtnDelete(row);
            }
        
        });
    }
    public void chageTextColour(){
        correctBtn.setForeground(Color.WHITE);
        discardBtn.setForeground(Color.WHITE);
    }
    
    public void proceedBtnActionColour(){
        correctBtn.setBackground(Color.BLUE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        correctBtn = new successBtn.ActionSelectBtn();
        discardBtn = new successBtn.ActionSelectBtn();

        correctBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct2.png"))); // NOI18N
        correctBtn.setText("   Proceed");
        correctBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        correctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correctBtnActionPerformed(evt);
            }
        });

        discardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/discardBtnImage.png"))); // NOI18N
        discardBtn.setText("   Discard");
        discardBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(correctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(correctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(discardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void correctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correctBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correctBtnActionPerformed

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discardBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private successBtn.ActionSelectBtn correctBtn;
    private successBtn.ActionSelectBtn discardBtn;
    // End of variables declaration//GEN-END:variables
}
