/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car.rental.system;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import raven.cell.TableActionCellEditor;
import raven.cell.TableActionCellRender;
import raven.cell.TableActionEvent;

/**
 *
 * @author Akila
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     * 
     * 
     
     */
    
    
    private int tableSelectedIndex=0;
    private String clickedIndexID="";
    private String currentPageHolder="dashboardPage";
    private EmployeeData employee1=null;
    public AdminPage() {
        initComponents();
//        loadOwnerData("ALL");
        employee1=new EmployeeData();
        employee1.loadEmployeeData("all", null, vehicalOwnerTable, null);
        renderCarTable();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                System.out.println("Edit row : " + row);
                if (CarTable.isEditing()) {
                    editSelectedCarData(row);
                }else if(vehicalOwnerTable.isEditing()){
                    System.out.println("Car table edit check   "+CarTable.isEditing());
                    editSelectedEmployeeData(row);
                }else if(discountTable.isEditing()){
                    System.out.println("edit dis available");
                    editSelectedDiscountData(row);
                }
                
            }

            @Override
            public void onDelete(int row) {
                System.out.println("Delete row : " + row);
                if (vehicalOwnerTable.isEditing()) {
                    vehicalOwnerTable.getCellEditor().stopCellEditing();
                }
                
                
               int resultofDelete= JOptionPane.showConfirmDialog(null,"Are you sure that you want to delete record","Deleting Confirmation",
                       JOptionPane.YES_NO_OPTION);
                if (resultofDelete==0) {
                    deleteSelectedRaw(row);
                }
                
            }

        };
        
        
       
        vehicalOwnerTable.getColumnModel().getColumn(9).setCellRenderer(new TableActionCellRender());
        vehicalOwnerTable.getColumnModel().getColumn(9).setCellEditor(new TableActionCellEditor(event));
        
        
        
        discountTable.getColumnModel().getColumn(4).setCellRenderer(new TableActionCellRender());
        discountTable.getColumnModel().getColumn(4).setCellEditor(new TableActionCellEditor(event));
        
        
        CarTable.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRender());
        CarTable.getColumnModel().getColumn(6).setCellRenderer(new tableImageCellRender());
        CarTable.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditor(event));
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    private void loadOwnerData(String searchType){
//        try {
//            DefaultTableModel ownerTableLoad=(DefaultTableModel)vehicalOwnerTable.getModel();
//            ownerTableLoad.getDataVector().removeAllElements();
//            ownerTableLoad.fireTableDataChanged();
//            
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
//            String s="";
//            if (searchType.equalsIgnoreCase("all")) {
//                s="select empID, role, firstname,lastname,NIC,email,city from employee";
//            }else{
//                s="select empID,role, firstname,lastname,NIC,email,city from employee where role=\""+searchType+"\"";
//            }
//            
//            PreparedStatement ps = con.prepareStatement(s);
//            ResultSet rs=ps.executeQuery();
//            while (rs.next()) {                
//                String empID=rs.getString("empID");
//                System.out.println("Substring check "+empID.substring(0,4));
//                String sd="select phoneNo from employeephone where empID=\""+empID+"\"";
//                PreparedStatement psd = con.prepareStatement(sd);
//                ResultSet numberResult=psd.executeQuery();
//                String[] numberArray=new String[2];
//                int count=0;
//                while (numberResult.next()) {                    
//                    numberArray[count]=numberResult.getString("phoneNo");
//                    count++;
//                }
//                psd.close();
//                numberResult.close();
//                String role=rs.getString("role");
//                String Fname=rs.getString("FirstName");
//                String Lname=rs.getString("lastName");
//                String NICno=rs.getString("NIC");
//                String email=rs.getString("Email");
//                String city=rs.getString("city");
//               
//                String[] ownerData={empID,Fname,Lname,role,email,NICno,city,numberArray[0],numberArray[1]};
//                
//                ownerTableLoad.addRow(ownerData);
//
//            }
//            rs.close();
//            ps.close();
//            con.close();
// 
//        } catch (Exception e) {
//            System.out.println(e);
//        }
//    }
    
    
    private void deleteSelectedRaw(int rawNo){
        try {

        DefaultTableModel carModel=(DefaultTableModel) CarTable.getModel();
        DefaultTableModel ownerTableclicked=(DefaultTableModel)vehicalOwnerTable.getModel();
        DefaultTableModel discountTableclicked=(DefaultTableModel)discountTable.getModel();
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
        
        String deletePhoneNoRaw="";
        Statement st=con.createStatement();
        System.out.println("Clicked indez  "+clickedIndexID);
            
        if (currentPageHolder.equalsIgnoreCase("CarPage")) {
                    clickedIndexID=(String) carModel.getValueAt(rawNo, 0);
                    deletePhoneNoRaw="delete from cars where CarNumber=\""+clickedIndexID+"\"";
                    st.executeUpdate(deletePhoneNoRaw);
                    carModel.removeRow(rawNo);
            
        }else if(currentPageHolder.equalsIgnoreCase("employeePage")){
                    clickedIndexID=(String) ownerTableclicked.getValueAt(rawNo, 0);
                    deletePhoneNoRaw="delete from employeephone where empId=\""+clickedIndexID+"\"";
                    st.executeUpdate(deletePhoneNoRaw);
                    String deleteRaw="delete from employee where empId=\""+clickedIndexID+"\"";
                    st.executeUpdate(deleteRaw);
                    ownerTableclicked.removeRow(rawNo);
        }
        else if(currentPageHolder.equalsIgnoreCase("discountPage")){
                    clickedIndexID=(String) discountTable.getValueAt(rawNo, 0);
                    deletePhoneNoRaw="delete from discount where discountID=\""+clickedIndexID+"\"";
                    st.executeUpdate(deletePhoneNoRaw);
                    discountTableclicked.removeRow(rawNo);
        }
         
        con.close();
        } catch (Exception e) {
            System.out.println("Error from adminpanel 154  "+e);
        }
        
    }
    private void editSelectedEmployeeData(int raw){
        DefaultTableModel ownerTableclicked=(DefaultTableModel)vehicalOwnerTable.getModel();
        clickedIndexID=(String) ownerTableclicked.getValueAt(raw, 0);
        try {
            
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
//            String singleData="select * from employee where empID=\""+clickedIndexID+"\"";
//            PreparedStatement ps = con.prepareStatement(singleData);
//            ResultSet rs=ps.executeQuery();
//            
//            String singleDataPhoneNumbers="select * from employeephone where empID=\""+clickedIndexID+"\"";
//            PreparedStatement psnumbers = con.prepareStatement(singleDataPhoneNumbers);
//            ResultSet rs2=psnumbers.executeQuery();
//            
            CustomerRegistrationForm form1=new CustomerRegistrationForm(clickedIndexID,"employee",null);
            form1.setVisible(true);
            
//            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    private void editSelectedCarData(int raw){
        DefaultTableModel CarTableclicked=(DefaultTableModel)CarTable.getModel();
        clickedIndexID=(String) CarTableclicked.getValueAt(raw, 0);
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
            String singleData="select * from cars where CarNumber=\""+clickedIndexID+"\"";
            PreparedStatement ps = con.prepareStatement(singleData);
            ResultSet rs=ps.executeQuery();
            
           
            CarAddingPanel carAdd1=new CarAddingPanel(rs);
            carAdd1.setVisible(true);
            
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    private void editSelectedDiscountData(int raw){
        DefaultTableModel discountclicked=(DefaultTableModel)discountTable.getModel();
        clickedIndexID=(String) discountclicked.getValueAt(raw, 0);
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
            String singleData="select * from discount where discountID=\""+clickedIndexID+"\"";
            PreparedStatement ps = con.prepareStatement(singleData);
            ResultSet rs=ps.executeQuery();
            
           
            DiscountAdder disc1=new DiscountAdder(rs);
            disc1.setVisible(true);
            
            con.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    
    
    
    
    private void renderCarTable(){
        try {
            DefaultTableModel CartableLoad=(DefaultTableModel)CarTable.getModel();
            CartableLoad.getDataVector().removeAllElements();
            CartableLoad.fireTableDataChanged();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
            String s="select * from cars";
            PreparedStatement ps = con.prepareStatement(s);
            ResultSet rs=ps.executeQuery();
            
            while (rs.next()) {            
                String car_keyValue=rs.getString("CarNumber");
                String car_type=rs.getString("CarType");
                String car_model=rs.getString("CarModel");
                String seat_no=rs.getString("SeatNo");
                String ac_Type=rs.getString("ACType");
                String fuel_type=rs.getString("FuelType"); 
                byte[] img=rs.getBytes("CarImage");
                
                ImageIcon image=new ImageIcon(img);
                Image im=image.getImage();
                Image myimage=im.getScaledInstance(120, 100, Image.SCALE_SMOOTH);
                ImageIcon newimage=new ImageIcon(myimage);
                
                JLabel imageLable=new JLabel();
                imageLable.setIcon(newimage);
               
               CartableLoad.addRow(new Object[]{car_keyValue,car_model,car_type,seat_no,ac_Type,fuel_type,imageLable});

            }
            rs.close();
            ps.close();
            con.close();
 
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    
    
    private void renderDiscountTable(){
        try {
            DefaultTableModel discountTableRender=(DefaultTableModel)discountTable.getModel();
            discountTableRender.getDataVector().removeAllElements();
            discountTableRender.fireTableDataChanged();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalsystem", "root", "akila123");
            String s="select * from discount";
            PreparedStatement ps = con.prepareStatement(s);
            ResultSet rs=ps.executeQuery();
            
            while (rs.next()) {            
                String discountID=rs.getString("discountID");
                String discountName=rs.getString("discountName");
                String discountPrecentage=rs.getString("precentage");
                String discountDiscription=rs.getString("Description");
                
                
               
               
               discountTableRender.addRow(new String[]{discountID,discountName,discountPrecentage,discountDiscription});

            }
            rs.close();
            ps.close();
            con.close();
 
        } catch (Exception e) {
            System.out.println("Discount Table Render "+e);
        }
    }
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidepanelAdminboard = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        DashboardPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        CarAddingPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CarTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CarSearchBar = new javax.swing.JTextField();
        searchCarIcon = new javax.swing.JButton();
        discountPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        discountTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        vehicalOwnerpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicalOwnerTable = new javax.swing.JTable();
        employeeSearchTextGetter = new javax.swing.JTextField();
        employeeSearchBtn = new javax.swing.JButton();
        employeeTypeSelector = new javax.swing.JComboBox<>();
        selectQueryEmp = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        vehicalownerbtn = new javax.swing.JButton();
        discountbtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidepanelAdminboard.setBackground(new java.awt.Color(28, 78, 128));

        javax.swing.GroupLayout SidepanelAdminboardLayout = new javax.swing.GroupLayout(SidepanelAdminboard);
        SidepanelAdminboard.setLayout(SidepanelAdminboardLayout);
        SidepanelAdminboardLayout.setHorizontalGroup(
            SidepanelAdminboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        SidepanelAdminboardLayout.setVerticalGroup(
            SidepanelAdminboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(SidepanelAdminboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 60));

        jTabbedPane1.setBackground(new java.awt.Color(153, 153, 255));

        DashboardPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Dashboard");

        jPanel2.setBackground(new java.awt.Color(20, 90, 45));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Number Of Customers");

        jPanel3.setBackground(new java.awt.Color(28, 128, 64));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("50");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jPanel4.setBackground(new java.awt.Color(20, 90, 45));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pending Reservations");

        jPanel5.setBackground(new java.awt.Color(28, 128, 64));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("50");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        jPanel6.setBackground(new java.awt.Color(20, 90, 45));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Proceeded Reservations");

        jPanel7.setBackground(new java.awt.Color(28, 128, 64));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("50");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardPanelLayout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(554, Short.MAX_VALUE))
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel6)
                .addGap(39, 39, 39)
                .addGroup(DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", DashboardPanel);

        CarAddingPanel.setBackground(new java.awt.Color(241, 241, 241));

        CarTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Number", "Car Model", "Car Type", "Seat No", "AC Type", "Fuel Type", "Image", "Settings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarTable.setRowHeight(30);
        CarTable.setSelectionBackground(new java.awt.Color(28, 78, 128));
        jScrollPane6.setViewportView(CarTable);

        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Car adding Panel");

        jButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton3.setText("Add Car");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        searchCarIcon.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        searchCarIcon.setText("Search");

        javax.swing.GroupLayout CarAddingPanelLayout = new javax.swing.GroupLayout(CarAddingPanel);
        CarAddingPanel.setLayout(CarAddingPanelLayout);
        CarAddingPanelLayout.setHorizontalGroup(
            CarAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarAddingPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(CarAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarAddingPanelLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(504, 504, 504)
                        .addComponent(CarSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CarAddingPanelLayout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        CarAddingPanelLayout.setVerticalGroup(
            CarAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarAddingPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CarAddingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CarSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("discount", CarAddingPanel);

        discountPanel.setBackground(new java.awt.Color(241, 241, 241));

        discountTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        discountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Discount ID", "Discount Name", "Precentage", "Description", "Settings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        discountTable.setRowHeight(30);
        discountTable.setSelectionBackground(new java.awt.Color(28, 78, 128));
        jScrollPane2.setViewportView(discountTable);
        if (discountTable.getColumnModel().getColumnCount() > 0) {
            discountTable.getColumnModel().getColumn(3).setResizable(false);
            discountTable.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Discount panel");

        jButton1.setText("Add Discount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout discountPanelLayout = new javax.swing.GroupLayout(discountPanel);
        discountPanel.setLayout(discountPanelLayout);
        discountPanelLayout.setHorizontalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(discountPanelLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(539, 539, 539)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        discountPanelLayout.setVerticalGroup(
            discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(discountPanelLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(discountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("discount", discountPanel);

        vehicalOwnerpanel.setBackground(new java.awt.Color(241, 241, 241));

        vehicalOwnerTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicalOwnerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Role", "Email", "NIC", "City", "Phone No 1", "Phone No 2", "Settings"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vehicalOwnerTable.setRowHeight(30);
        vehicalOwnerTable.setSelectionBackground(new java.awt.Color(28, 78, 128));
        vehicalOwnerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicalOwnerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehicalOwnerTable);
        if (vehicalOwnerTable.getColumnModel().getColumnCount() > 0) {
            vehicalOwnerTable.getColumnModel().getColumn(0).setResizable(false);
            vehicalOwnerTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            vehicalOwnerTable.getColumnModel().getColumn(4).setResizable(false);
            vehicalOwnerTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            vehicalOwnerTable.getColumnModel().getColumn(5).setResizable(false);
            vehicalOwnerTable.getColumnModel().getColumn(7).setResizable(false);
            vehicalOwnerTable.getColumnModel().getColumn(7).setPreferredWidth(50);
            vehicalOwnerTable.getColumnModel().getColumn(8).setResizable(false);
            vehicalOwnerTable.getColumnModel().getColumn(8).setPreferredWidth(50);
        }

        employeeSearchTextGetter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchTextGetterActionPerformed(evt);
            }
        });
        employeeSearchTextGetter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                employeeSearchTextGetterKeyTyped(evt);
            }
        });

        employeeSearchBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        employeeSearchBtn.setText("Search");
        employeeSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchBtnActionPerformed(evt);
            }
        });

        employeeTypeSelector.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        employeeTypeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add Admin", "Add Cashier", "Add Driver", "Add Vehical Owner" }));
        employeeTypeSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTypeSelectorActionPerformed(evt);
            }
        });

        selectQueryEmp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectQueryEmp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Show All Employees", "Show All Admins", "Show All Cashiers", "Show All Drivers", "Show All Vehical Owners" }));
        selectQueryEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectQueryEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vehicalOwnerpanelLayout = new javax.swing.GroupLayout(vehicalOwnerpanel);
        vehicalOwnerpanel.setLayout(vehicalOwnerpanelLayout);
        vehicalOwnerpanelLayout.setHorizontalGroup(
            vehicalOwnerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicalOwnerpanelLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(vehicalOwnerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehicalOwnerpanelLayout.createSequentialGroup()
                        .addComponent(employeeTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeSearchTextGetter, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectQueryEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        vehicalOwnerpanelLayout.setVerticalGroup(
            vehicalOwnerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehicalOwnerpanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(vehicalOwnerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeSearchTextGetter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeTypeSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectQueryEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jTabbedPane1.addTab("vehicalowner", vehicalOwnerpanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1230, 710));

        jPanel1.setBackground(new java.awt.Color(28, 78, 128));

        vehicalownerbtn.setBackground(new java.awt.Color(28, 78, 128));
        vehicalownerbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        vehicalownerbtn.setForeground(new java.awt.Color(255, 255, 255));
        vehicalownerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cars3.png"))); // NOI18N
        vehicalownerbtn.setText("Employee");
        vehicalownerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicalownerbtnActionPerformed(evt);
            }
        });

        discountbtn.setBackground(new java.awt.Color(28, 78, 128));
        discountbtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        discountbtn.setForeground(new java.awt.Color(255, 255, 255));
        discountbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cars3.png"))); // NOI18N
        discountbtn.setText("Discount");
        discountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discountbtnActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(28, 78, 128));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cars3.png"))); // NOI18N
        jButton6.setText("Cars");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(28, 78, 128));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cars3.png"))); // NOI18N
        jButton7.setText("Dashboard");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicalownerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(vehicalownerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(discountbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vehicalownerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicalownerbtnActionPerformed
        // TODO add your handling code here:
        currentPageHolder="employeePage";
//        loadOwnerData("all");
          employee1.loadEmployeeData("all", null, vehicalOwnerTable, null);
        jTabbedPane1.setSelectedIndex(3);
        if (CarTable.isEditing()) {
            CarTable.getCellEditor().stopCellEditing();
        }
        
    }//GEN-LAST:event_vehicalownerbtnActionPerformed

    private void discountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discountbtnActionPerformed
        jTabbedPane1.setSelectedIndex(2);
        renderDiscountTable();
        currentPageHolder="discountPage";
        // TODO add your handling code here:
    }//GEN-LAST:event_discountbtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        currentPageHolder="CarPage";
        renderCarTable();
        
        jTabbedPane1.setSelectedIndex(1);
        if (vehicalOwnerTable.isEditing()) {
            vehicalOwnerTable.getCellEditor().stopCellEditing();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CarAddingPanel carUpdate1=new CarAddingPanel();
        carUpdate1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void employeeTypeSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTypeSelectorActionPerformed
        // TODO add your handling code here:
        System.out.println(employeeTypeSelector.getSelectedIndex());
        if (employeeTypeSelector.getSelectedIndex()==3) {
            System.out.println("Vowner Selected");
            CustomerRegistrationForm c1=new CustomerRegistrationForm(null,"employee","VOwner");
            c1.SetRegistrationFrameTitle("Car Owner Registration", "Add Owner");
            c1.setVisible(true);
        }else if (employeeTypeSelector.getSelectedIndex()==2) {
            CustomerRegistrationForm c1=new CustomerRegistrationForm(null,"employee","Driver");
            c1.SetRegistrationFrameTitle("Driver Registration", "Add Driver");
            c1.setVisible(true);
        }else if (employeeTypeSelector.getSelectedIndex()==1) {
            CustomerRegistrationForm c1=new CustomerRegistrationForm(null,"employee","Cashier");
            c1.SetRegistrationFrameTitle("Cashier Registration", "Add Cashier");
            c1.setVisible(true);
        }else if (employeeTypeSelector.getSelectedIndex()==0) {
            CustomerRegistrationForm c1=new CustomerRegistrationForm(null,"employee","Admin");
            c1.SetRegistrationFrameTitle("Admin Registration", "Add Admin");
            c1.setVisible(true);
        }
    }//GEN-LAST:event_employeeTypeSelectorActionPerformed

    private void selectQueryEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectQueryEmpActionPerformed
        // TODO add your handling code here:
        if (selectQueryEmp.getSelectedIndex()==0) {
//            loadOwnerData("All");
              employee1.loadEmployeeData("all", null, vehicalOwnerTable, null);
        }else if(selectQueryEmp.getSelectedIndex()==1){
//            loadOwnerData("Admin");
            employee1.loadEmployeeData("all", null, vehicalOwnerTable, "Admin");
        }else if(selectQueryEmp.getSelectedIndex()==2){
//            loadOwnerData("Cashier");
            employee1.loadEmployeeData("all", null, vehicalOwnerTable, "Cashier");
        }else if(selectQueryEmp.getSelectedIndex()==3){
//            loadOwnerData("Driver");
            employee1.loadEmployeeData("all", null, vehicalOwnerTable, "Driver");
        }else if(selectQueryEmp.getSelectedIndex()==4){
//            loadOwnerData("VOwner");
            employee1.loadEmployeeData("all", null, vehicalOwnerTable, "VOwner");
        }
    }//GEN-LAST:event_selectQueryEmpActionPerformed

    private void vehicalOwnerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicalOwnerTableMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_vehicalOwnerTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DiscountAdder di=new DiscountAdder();
        di.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void employeeSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchBtnActionPerformed
        // TODO add your handling code here:
        employee1.searchEmployee(employeeSearchTextGetter.getText(),vehicalOwnerTable);
    }//GEN-LAST:event_employeeSearchBtnActionPerformed

    private void employeeSearchTextGetterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchTextGetterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSearchTextGetterActionPerformed

    private void employeeSearchTextGetterKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_employeeSearchTextGetterKeyTyped
        // TODO add your handling code here:
        employee1.searchEmployee(employeeSearchTextGetter.getText(),vehicalOwnerTable);
    }//GEN-LAST:event_employeeSearchTextGetterKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarAddingPanel;
    private javax.swing.JTextField CarSearchBar;
    private javax.swing.JTable CarTable;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JPanel SidepanelAdminboard;
    private javax.swing.JPanel discountPanel;
    private javax.swing.JTable discountTable;
    private javax.swing.JButton discountbtn;
    private javax.swing.JButton employeeSearchBtn;
    private javax.swing.JTextField employeeSearchTextGetter;
    private javax.swing.JComboBox<String> employeeTypeSelector;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton searchCarIcon;
    private javax.swing.JComboBox<String> selectQueryEmp;
    private javax.swing.JTable vehicalOwnerTable;
    private javax.swing.JPanel vehicalOwnerpanel;
    private javax.swing.JButton vehicalownerbtn;
    // End of variables declaration//GEN-END:variables
}
