/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.rental.system;

import javax.swing.JLabel;

/**
 *
 * @author Akila
 */
public class Card extends javax.swing.JPanel {

    String keyvalue;
    private boolean viewMoreBtnStatus;

    public boolean isViewMoreBtnStatus() {
        return viewMoreBtnStatus;
    }

    public void setViewMoreBtnStatus(boolean viewMoreBtnStatus) {
        this.viewMoreBtnStatus = viewMoreBtnStatus;
    }

    /**
     * Creates new form card
     */
    public Card() {
        initComponents();
    }

    public JLabel getCarTypeContainer() {
        return CarTypeContainer;
    }

    public void setCarTypeContainer(JLabel CarTypeContainer) {
        this.CarTypeContainer = CarTypeContainer;
    }

    public JLabel getAcTypeContainer() {
        return acTypeContainer;
    }

    public void setAcTypeContainer(JLabel acTypeContainer) {
        this.acTypeContainer = acTypeContainer;
    }

    public JLabel getCarImageContainer() {
        return carImageContainer;
    }

    public void setCarImageContainer(JLabel carImageContainer) {
        this.carImageContainer = carImageContainer;
    }

    public JLabel getCar_ModelContainer() {
        return car_ModelContainer;
    }

    public void setCar_ModelContainer(JLabel car_ModelContainer) {
        this.car_ModelContainer = car_ModelContainer;
    }

    public JLabel getFuelTypeContainer() {
        return fuelTypeContainer;
    }

    public void setFuelTypeContainer(JLabel fuelTypeContainer) {
        this.fuelTypeContainer = fuelTypeContainer;
    }

    public JLabel getSeatCountContainer() {
        return seatCountContainer;
    }

    public void setSeatCountContainer(JLabel seatCountContainer) {
        this.seatCountContainer = seatCountContainer;
    }

    private ItemModel data;

    
    /**
     * set car data to the corresponding card
     * @param data 
     */
    public void setData(ItemModel data) {
        this.data = data;
        CarTypeContainer.setText(data.car_type);
        car_ModelContainer.setText(data.car_model);
        seatCountContainer.setText(data.seat_no);
        acTypeContainer.setText(data.ac_Type);
        fuelTypeContainer.setText(data.fuel_type);
        carImageContainer.setIcon(data.carimage);
        keyvalue = data.car_keyValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        seatCountContainer = new javax.swing.JLabel();
        car_ModelContainer = new javax.swing.JLabel();
        carImageContainer = new javax.swing.JLabel();
        CarTypeContainer = new javax.swing.JLabel();
        acTypeContainer = new javax.swing.JLabel();
        fuelTypeContainer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 78, 128));
        setMaximumSize(new java.awt.Dimension(167, 228));

        jPanel1.setBackground(new java.awt.Color(28, 128, 78));

        seatCountContainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seatCountContainer.setForeground(new java.awt.Color(255, 255, 255));
        seatCountContainer.setText("s");

        car_ModelContainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        car_ModelContainer.setForeground(new java.awt.Color(255, 255, 255));
        car_ModelContainer.setText("Model");

        carImageContainer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carImageContainer.setForeground(new java.awt.Color(0, 0, 0));
        carImageContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        CarTypeContainer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CarTypeContainer.setForeground(new java.awt.Color(255, 255, 255));
        CarTypeContainer.setText("Car Type");

        acTypeContainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acTypeContainer.setForeground(new java.awt.Color(255, 255, 255));
        acTypeContainer.setText("ac");

        fuelTypeContainer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelTypeContainer.setForeground(new java.awt.Color(255, 255, 255));
        fuelTypeContainer.setText("f");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seatwhite.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fuelWhite.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ACWhite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CarTypeContainer)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fuelTypeContainer)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(car_ModelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatCountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(carImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(car_ModelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuelTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatCountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarTypeContainer;
    private javax.swing.JLabel acTypeContainer;
    private javax.swing.JLabel carImageContainer;
    private javax.swing.JLabel car_ModelContainer;
    private javax.swing.JLabel fuelTypeContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel seatCountContainer;
    // End of variables declaration//GEN-END:variables
}
