/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package car.rental.system;

import javax.swing.JLabel;

/**
 *
 * @author Akila
 */
public class Card extends javax.swing.JPanel {
    
    
    
    String keyvalue;
    private boolean viewMoreBtnStatus;

    public boolean isViewMoreBtnStatus() {
        return viewMoreBtnStatus;
    }

    public void setViewMoreBtnStatus(boolean viewMoreBtnStatus) {
        this.viewMoreBtnStatus = viewMoreBtnStatus;
    }

    /**
     * Creates new form card
     */
    public Card() {
        initComponents();
    }

    public JLabel getCarTypeContainer() {
        return CarTypeContainer;
    }

    public void setCarTypeContainer(JLabel CarTypeContainer) {
        this.CarTypeContainer = CarTypeContainer;
    }

    public JLabel getAcTypeContainer() {
        return acTypeContainer;
    }

    public void setAcTypeContainer(JLabel acTypeContainer) {
        this.acTypeContainer = acTypeContainer;
    }

    public JLabel getCarImageContainer() {
        return carImageContainer;
    }

    public void setCarImageContainer(JLabel carImageContainer) {
        this.carImageContainer = carImageContainer;
    }

    public JLabel getCar_ModelContainer() {
        return car_ModelContainer;
    }

    public void setCar_ModelContainer(JLabel car_ModelContainer) {
        this.car_ModelContainer = car_ModelContainer;
    }

    public JLabel getFuelTypeContainer() {
        return fuelTypeContainer;
    }

    public void setFuelTypeContainer(JLabel fuelTypeContainer) {
        this.fuelTypeContainer = fuelTypeContainer;
    }

    public JLabel getSeatCountContainer() {
        return seatCountContainer;
    }

    public void setSeatCountContainer(JLabel seatCountContainer) {
        this.seatCountContainer = seatCountContainer;
    }
    
    
    private ItemModel data;
    public void setData(ItemModel data){
        this.data=data;
        CarTypeContainer.setText(data.car_type);
        car_ModelContainer.setText(data.car_model);
        seatCountContainer.setText("Seat No "+data.seat_no);
        acTypeContainer.setText(data.ac_Type);
        fuelTypeContainer.setText("Fuel Type "+data.fuel_type);
        carImageContainer.setIcon(data.carimage);
        keyvalue=data.car_keyValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carImageContainer = new javax.swing.JLabel();
        acTypeContainer = new javax.swing.JLabel();
        CarTypeContainer = new javax.swing.JLabel();
        seatCountContainer = new javax.swing.JLabel();
        fuelTypeContainer = new javax.swing.JLabel();
        car_ModelContainer = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(167, 228));

        carImageContainer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        carImageContainer.setForeground(new java.awt.Color(0, 0, 0));
        carImageContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        acTypeContainer.setForeground(new java.awt.Color(0, 0, 0));
        acTypeContainer.setText("AC/NON AC");

        CarTypeContainer.setForeground(new java.awt.Color(0, 0, 0));
        CarTypeContainer.setText("Car Type");

        seatCountContainer.setForeground(new java.awt.Color(0, 0, 0));
        seatCountContainer.setText("Seat Count");

        fuelTypeContainer.setForeground(new java.awt.Color(0, 0, 0));
        fuelTypeContainer.setText("Fuel Type");

        car_ModelContainer.setForeground(new java.awt.Color(0, 0, 0));
        car_ModelContainer.setText("Model");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(car_ModelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatCountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(carImageContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(car_ModelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatCountContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelTypeContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CarTypeContainer;
    private javax.swing.JLabel acTypeContainer;
    private javax.swing.JLabel carImageContainer;
    private javax.swing.JLabel car_ModelContainer;
    private javax.swing.JLabel fuelTypeContainer;
    private javax.swing.JLabel seatCountContainer;
    // End of variables declaration//GEN-END:variables
}
