/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car.rental.system;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Akila
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */
    public SplashScreen() {
        initComponents();
    }
    
    
    /**
     * change text when splash goes >50%
     */
    public void changeText(){
        splashtext.setText("High Service for  Every Customer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        progressBarshower = new javax.swing.JProgressBar();
        splashtext = new javax.swing.JLabel();
        presentageValue = new javax.swing.JLabel();
        backgroundSplash = new javax.swing.JLabel();
        backgroundsplash2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(892, 444));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(892, 454));
        jPanel1.setPreferredSize(new java.awt.Dimension(930, 454));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBarshower.setBackground(new java.awt.Color(0, 255, 255));
        progressBarshower.setForeground(new java.awt.Color(28, 78, 128));
        jPanel1.add(progressBarshower, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 900, -1));

        splashtext.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        splashtext.setForeground(new java.awt.Color(0, 0, 0));
        splashtext.setText("Easy and Fast way to Rent your Car");
        jPanel1.add(splashtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 600, 60));

        presentageValue.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(presentageValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 60, 30));

        backgroundSplash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash1.png"))); // NOI18N
        backgroundSplash.setIconTextGap(0);
        backgroundSplash.setInheritsPopupMenu(false);
        jPanel1.add(backgroundSplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundsplash2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/splash2.png"))); // NOI18N
        backgroundsplash2.setText("jLabel1");
        jPanel1.add(backgroundsplash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

                SplashScreen splash = new SplashScreen();   //create splash screen object
                splash.setVisible(true);

                for (int i = 0; i <= 100; i++) {
                    try {
                        Thread.sleep(50);
                        splash.presentageValue.setText(String.valueOf(i) + "%");  //splash screen visibility
                        splash.progressBarshower.setValue(i);
                        if (i > 50) {
                            splash.backgroundSplash.setVisible(false);   //change splash 2nd image
                            splash.changeText();   // change splash screen text
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(CarRentalSystem.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                splash.dispose();
                CustomSearch1 s1 = new CustomSearch1();   //open car search window
                s1.setVisible(true);

            }
        

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel backgroundSplash;
    public javax.swing.JLabel backgroundsplash2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel presentageValue;
    public javax.swing.JProgressBar progressBarshower;
    private javax.swing.JLabel splashtext;
    // End of variables declaration//GEN-END:variables
}
