/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car.rental.system;

/**
 *
 * @author Akila
 */
public class VOwnerRegistrationFrom extends javax.swing.JFrame {

    VehicalOwner owner1=null;
    
    public VOwnerRegistrationFrom() {
        initComponents();
        owner1=new VehicalOwner();
        defaultErrorShowerMsgEditor(new String[]{"","","","","",""});    //set all default value to null
    }
    
    public VOwnerRegistrationFrom(String ClickedIndex){
        initComponents();
        setUpdateComponents(ClickedIndex);
        defaultErrorShowerMsgEditor(new String[]{"","","","","",""});
    }
    
    
    
    //set all update components
    private void setUpdateComponents(String clickedIndex){
        owner1=new VehicalOwner();
        owner1.getSingleOwnerData(clickedIndex);
        ownerFirstName.setText(owner1.getFirstName());
        ownerLastName.setText(owner1.getLastName());
        ownerEmail.setText(owner1.getEmail());
        ownerCity.setText(owner1.getCity());
        ownerNIC.setText(owner1.getNIC());
        OwnerPhoneNo.setText(owner1.getPhoneNo1());
        addbtnOwner.setText("Update Owner");
    }
    
    
    
    private void updateDetails(){
        owner1.setFirstName(ownerFirstName.getText());
        owner1.setLastName(ownerLastName.getText());
        owner1.setEmail(ownerEmail.getText());
        owner1.setCity(ownerCity.getText());
        owner1.setNIC(ownerNIC.getText());
        owner1.setPhoneNo1(OwnerPhoneNo.getText());
        owner1.updateOwnerData();
        
        
    }
    
    
    private void addDetails(){
        owner1.setFirstName(ownerFirstName.getText());
        owner1.setLastName(ownerLastName.getText());
        owner1.setEmail(ownerEmail.getText());
        owner1.setCity(ownerCity.getText());
        owner1.setNIC(ownerNIC.getText());
        owner1.setPhoneNo1(OwnerPhoneNo.getText());
        owner1.InsertVOwnerData();
        CarRentalSystem.closeWindows(this);
        
        
    }
    
    private void defaultErrorShowerMsgEditor(String[] arr){
        FirstNameErrorShower.setText(arr[0]);
        lastNameErrorShower.setText(arr[1]);
        emailErrorShower.setText(arr[2]);
        cityErrorShower.setText(arr[3]);
        NicErrorShower.setText(arr[4]);
        phoneNoErrorShower.setText(arr[5]);
    }
    
    private boolean validateInput(){
        defaultErrorShowerMsgEditor(new String[]{"","","","","",""});
        Validations v1=new Validations();
        String fnameError=v1.nameChecker(ownerFirstName.getText());
        String lNameError=v1.nameChecker(ownerLastName.getText());
        String emailError=v1.emailChecker(ownerEmail.getText());
        String cityError=v1.discountNameDescriptionValidator(ownerCity.getText());
        String nicError=v1.NICvalidate(ownerNIC.getText());
        String phoneNoError=v1.phoneNumberValidate(OwnerPhoneNo.getText());
        
        
        boolean result=fnameError.equalsIgnoreCase("") && lNameError.equalsIgnoreCase("") && emailError.equalsIgnoreCase("")
                && cityError.equalsIgnoreCase("") && nicError.equalsIgnoreCase("") && phoneNoError.equalsIgnoreCase("");
        
        if (result) {
            return true;
        }else{
            defaultErrorShowerMsgEditor(new String[]{fnameError,lNameError,emailError,cityError,nicError,phoneNoError});
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ownerLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ownerEmail = new javax.swing.JTextField();
        ownerFirstName = new javax.swing.JTextField();
        OwnerPhoneNo = new javax.swing.JTextField();
        ownerCity = new javax.swing.JTextField();
        ownerNIC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addbtnOwner = new javax.swing.JButton();
        driverAddingCancelation = new javax.swing.JButton();
        FirstNameErrorShower = new javax.swing.JLabel();
        lastNameErrorShower = new javax.swing.JLabel();
        emailErrorShower = new javax.swing.JLabel();
        cityErrorShower = new javax.swing.JLabel();
        NicErrorShower = new javax.swing.JLabel();
        phoneNoErrorShower = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(28, 78, 128));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 72, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ownerLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerLastNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Vehical Owner Registration");

        ownerFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerFirstNameActionPerformed(evt);
            }
        });

        ownerNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerNICActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("City");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Phone No1");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("NIC No");

        addbtnOwner.setText("Add Owner");
        addbtnOwner.setMinimumSize(new java.awt.Dimension(72, 23));
        addbtnOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnOwnerActionPerformed(evt);
            }
        });

        driverAddingCancelation.setText("Cancel");
        driverAddingCancelation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverAddingCancelationActionPerformed(evt);
            }
        });

        FirstNameErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FirstNameErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        FirstNameErrorShower.setText("jLabel5");

        lastNameErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lastNameErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        lastNameErrorShower.setText("jLabel5");

        emailErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        emailErrorShower.setText("jLabel5");

        cityErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cityErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        cityErrorShower.setText("jLabel5");

        NicErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NicErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        NicErrorShower.setText("jLabel5");

        phoneNoErrorShower.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNoErrorShower.setForeground(new java.awt.Color(255, 0, 0));
        phoneNoErrorShower.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addbtnOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(driverAddingCancelation, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OwnerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ownerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(phoneNoErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NicErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ownerEmail)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ownerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGap(63, 63, 63)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(ownerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(ownerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(FirstNameErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailErrorShower, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameErrorShower)
                    .addComponent(lastNameErrorShower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(ownerEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailErrorShower)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addComponent(ownerCity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(cityErrorShower)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(ownerNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NicErrorShower)
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OwnerPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNoErrorShower)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtnOwner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driverAddingCancelation, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 660, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void driverAddingCancelationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverAddingCancelationActionPerformed
        CarRentalSystem.closeWindows(this);
    }//GEN-LAST:event_driverAddingCancelationActionPerformed

    private void addbtnOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnOwnerActionPerformed
        // TODO add your handling code here:
        if (addbtnOwner.getText().equalsIgnoreCase("Update Owner")) {
            if (validateInput()) {
                updateDetails();
                CarRentalSystem.closeWindows(this);
            }
            
            
        }else{
            if (validateInput()) {
                addDetails();
            }
            
        }
        
    }//GEN-LAST:event_addbtnOwnerActionPerformed

    private void ownerNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerNICActionPerformed

    private void ownerFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerFirstNameActionPerformed

    private void ownerLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ownerLastNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VOwnerRegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VOwnerRegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VOwnerRegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VOwnerRegistrationFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOwnerRegistrationFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstNameErrorShower;
    private javax.swing.JLabel NicErrorShower;
    private javax.swing.JTextField OwnerPhoneNo;
    private javax.swing.JButton addbtnOwner;
    private javax.swing.JLabel cityErrorShower;
    private javax.swing.JButton driverAddingCancelation;
    private javax.swing.JLabel emailErrorShower;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lastNameErrorShower;
    private javax.swing.JTextField ownerCity;
    private javax.swing.JTextField ownerEmail;
    private javax.swing.JTextField ownerFirstName;
    private javax.swing.JTextField ownerLastName;
    private javax.swing.JTextField ownerNIC;
    private javax.swing.JLabel phoneNoErrorShower;
    // End of variables declaration//GEN-END:variables
}
